apiVersion: v1
kind: Namespace
metadata:
  name: {{BRANCH}}-{{PROJECT_NAME}}
---
apiVersion: v1
kind: Secret
metadata:
  name: madlabsregistry-credential
  namespace: {{BRANCH}}-{{PROJECT_NAME}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5tYWRsYWJzLmNvbS5iciI6IHsKCQkJImF1dGgiOiAiZFhObGNsOXlaV2RwYzNSeWVUcGxNMGdqUUNGZk4wMVBMa29zUTJNNGVsVXlNUzFqIgoJCX0KCX0KfQ== ### config.json in base64
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{PROJECT_NAME}}
  namespace: {{BRANCH}}-{{PROJECT_NAME}}
spec:
  selector:
    matchLabels:
      app: {{PROJECT_NAME}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{PROJECT_NAME}}
    spec:
      containers:
        - name: registry
          image: registry.madlabs.com.br/{{PROJECT_NAME}}:{{BRANCH}}-{{TAG}}
          resources:
            limits:
              memory: "128Mi"
              cpu: "0.2"
            requests:
              memory: "64Mi"
              cpu: "0.1"
          ports:
            - name: http
              containerPort: 80
      imagePullSecrets:
        - name: madlabsregistry-credential
---
apiVersion: v1
kind: Service
metadata:
  name: {{PROJECT_NAME}}
  namespace: {{BRANCH}}-{{PROJECT_NAME}}
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: {{PROJECT_NAME}}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{PROJECT_NAME}}
  namespace: {{BRANCH}}-{{PROJECT_NAME}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{PROJECT_NAME}}
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target: 
        type: Utilization
        averageUtilization: 80