apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-homolog-madlabs-com-br
  namespace: {{BRANCH}}-{{PROJECT_NAME}}
spec:
  dnsNames:
    - "homolog.madlabs.com.br"
  secretName: homolog-madlabs-com-br-tls
  issuerRef:
    name: staging-letsencrypt-cert-manager
    kind: ClusterIssuer